LICENSE_NAME="Apache-2.0"
PROJNAME_DOCUMENTS="xayn_back_office_sdk"
PROJNAME_USERS="xayn_front_office_sdk"
PKG_DOCUMENTS="com.xayn.backoffice"
PKG_USERS="com.xayn.frontoffice"
ID_DOCUMENTS="xayn_back_office_sdk"
ID_USERS="xayn_front_office_sdk"