/**
 * Personalization API For User Management
 * # User management The system identifies a user with only an id. There are two main endpoints: one that allows registering an interaction between a user and a document (a user clicked or liked a document), and one to retrieve a personalized set of documents for the user. The system needs a few user interactions with documents before it can generate a personalized list.  # Auth To authenticate with the API, a token will be provided.
 *
 * The version of the OpenAPI document: 1.0.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class UserInteractionType.
* @enum {}
* @readonly
*/
export default class UserInteractionType {
    
        /**
         * value: "positive"
         * @const
         */
        "positive" = "positive";

    

    /**
    * Returns a <code>UserInteractionType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/UserInteractionType} The enum <code>UserInteractionType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

