name: Generate SDKs

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code and run code generation
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: |
          Host github.com
            IdentityFile ~/.ssh/id_rsa_github
        if_key_exists: replace
      env:
        VERSION: ${{ github.ref }}
        ENDPOINT: ${{ secrets.ENDPOINT }}
        TOKEN_DOCUMENTS: ${{ secrets.TOKEN_DOCUMENTS }}
        TOKEN_USERS: ${{ secrets.TOKEN_USERS }}
      run: bash ./generate.sh
