name: Generate SDKs

on:
  push:
    refs:
      - refs/tags/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run code generation
      run: generate.sh
      env:
        VERSION: ${{ github.ref }}