name: Verify

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  verify-swift:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Verify Generation
      run: |
        ./test.sh swift

      env:
        VERSION: ${{ github.ref }}
        ENDPOINT: ${{ secrets.ENDPOINT }}
        TOKEN_DOCUMENTS: ${{ secrets.TOKEN_DOCUMENTS }}
        TOKEN_USERS: ${{ secrets.TOKEN_USERS }}

  verify-others:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Verify Generation
      run: |
        ./test.sh javascript
        ./test.sh java
      env:
        VERSION: ${{ github.ref }}
        ENDPOINT: ${{ secrets.ENDPOINT }}
        TOKEN_DOCUMENTS: ${{ secrets.TOKEN_DOCUMENTS }}
        TOKEN_USERS: ${{ secrets.TOKEN_USERS }}