name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.2.1
      with:
        version: 5.7.1
    - uses: actions/checkout@v2
    - name: Verify Generation
      run: bash ./test.sh
      env:
        VERSION: ${{ github.ref }}
        ENDPOINT: ${{ secrets.ENDPOINT }}
        TOKEN_DOCUMENTS: ${{ secrets.TOKEN_DOCUMENTS }}
        TOKEN_USERS: ${{ secrets.TOKEN_USERS }}