/**
 * Personalization API For User Management
 * # User management The system identifies a user with only an id. There are two main endpoints: one that allows registering an interaction between a user and a document (a user clicked or liked a document), and one to retrieve a personalized set of documents for the user. The system needs a few user interactions with documents before it can generate a personalized list.  # Auth To authenticate with the API, a token will be provided.
 *
 * The version of the OpenAPI document: 1.0.0-rc5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BaseError from './model/BaseError';
import PersonalizedDocumentData from './model/PersonalizedDocumentData';
import PersonalizedDocumentsError from './model/PersonalizedDocumentsError';
import PersonalizedDocumentsErrorAllOf from './model/PersonalizedDocumentsErrorAllOf';
import PersonalizedDocumentsResponse from './model/PersonalizedDocumentsResponse';
import UserInteractionData from './model/UserInteractionData';
import UserInteractionError from './model/UserInteractionError';
import UserInteractionErrorAllOf from './model/UserInteractionErrorAllOf';
import UserInteractionRequest from './model/UserInteractionRequest';
import UserInteractionType from './model/UserInteractionType';
import UsersApi from './com.xayn.users/UsersApi';


/**
* # User management The system identifies a user with only an id. There are two main endpoints: one that allows registering an interaction between a user and a document (a user clicked or liked a document), and one to retrieve a personalized set of documents for the user. The system needs a few user interactions with documents before it can generate a personalized list.  # Auth To authenticate with the API, a token will be provided..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var XaynUserManagementSdk = require('index'); // See note below*.
* var xxxSvc = new XaynUserManagementSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new XaynUserManagementSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new XaynUserManagementSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new XaynUserManagementSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BaseError model constructor.
     * @property {module:model/BaseError}
     */
    BaseError,

    /**
     * The PersonalizedDocumentData model constructor.
     * @property {module:model/PersonalizedDocumentData}
     */
    PersonalizedDocumentData,

    /**
     * The PersonalizedDocumentsError model constructor.
     * @property {module:model/PersonalizedDocumentsError}
     */
    PersonalizedDocumentsError,

    /**
     * The PersonalizedDocumentsErrorAllOf model constructor.
     * @property {module:model/PersonalizedDocumentsErrorAllOf}
     */
    PersonalizedDocumentsErrorAllOf,

    /**
     * The PersonalizedDocumentsResponse model constructor.
     * @property {module:model/PersonalizedDocumentsResponse}
     */
    PersonalizedDocumentsResponse,

    /**
     * The UserInteractionData model constructor.
     * @property {module:model/UserInteractionData}
     */
    UserInteractionData,

    /**
     * The UserInteractionError model constructor.
     * @property {module:model/UserInteractionError}
     */
    UserInteractionError,

    /**
     * The UserInteractionErrorAllOf model constructor.
     * @property {module:model/UserInteractionErrorAllOf}
     */
    UserInteractionErrorAllOf,

    /**
     * The UserInteractionRequest model constructor.
     * @property {module:model/UserInteractionRequest}
     */
    UserInteractionRequest,

    /**
     * The UserInteractionType model constructor.
     * @property {module:model/UserInteractionType}
     */
    UserInteractionType,

    /**
    * The UsersApi service constructor.
    * @property {module:com.xayn.users/UsersApi}
    */
    UsersApi
};
